### ISSUE TITLE
Can I provide upload function?

### ISSUE THREAD

**Issue by gssjl2008** [mohamnag/nginx-file-browser#10]
For example, with this function, it is very cool.

**Comment by mohamnag** [comment]
thanks for suggestion. The idea of this project was a simple readonly view to escape from all the discussions around permissions and access regulation. If you have a PR however, for the write functionality that can safely and easily turned off, I can take a look at it. don't really have the time for it personally.

**Comment by gssjl2008** [comment]
that's ok
