### ISSUE TITLE
Docker Container as non-root

### ISSUE THREAD

**Issue by adberger** [mohamnag/nginx-file-browser#7]
Hi there

Are there any plans to make this container image non-root?
Should be relatively easy AFAIK.

**Comment by mohamnag** [comment]
Hi,
it could be easy however needs testing and probably also fine tuning of the
upstream image (according to description of the nginx image it needs config
change). I'm unfortunately very busy at the moment, but any PR is welcome.

Regards

**Comment by mohamnag** [comment]
closing this as this is addressed by #8
