### ISSUE TITLE
Using autoindex_strapdown

### ISSUE THREAD

**Issue by jarbelix** [mohamnag/nginx-file-browser#9]
First I would like to congratulate you for the initiative to make such an application available.

I hope you don't take me the wrong way, but I'd like you to take a look at this proposal.

https://github.com/chuckhoupt/autoindex_strapdown

This would make nginx settings simpler and look simpler and more customizable.

**Comment by mohamnag** [comment]
thanks, if I'm not mistaken, that is for Apache and this project is for nginx right? also a reason for this simple UI is the fact that nginx was necessary one way or the other in the setup so these are two different pairs of shoes at the end.
